# CMAKE generated file: DO NOT EDIT!
# Generated by "KDevelop3" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/enni/simpleGL/libsgl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/enni/simpleGL/libsgl

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@echo "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enni/simpleGL/libsgl/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enni/simpleGL/libsgl/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named sgl

# Build rule for target.
sgl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sgl

# fast build rule for target.
sgl/fast:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/build

# target to build an object file
helper/sglcamera.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglcamera.o

# target to preprocess a source file
helper/sglcamera.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglcamera.i

# target to generate assembly for a file
helper/sglcamera.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglcamera.s

# target to build an object file
helper/sglclipplane.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglclipplane.o

# target to preprocess a source file
helper/sglclipplane.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglclipplane.i

# target to generate assembly for a file
helper/sglclipplane.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglclipplane.s

# target to build an object file
helper/sgldisplist.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgldisplist.o

# target to preprocess a source file
helper/sgldisplist.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgldisplist.i

# target to generate assembly for a file
helper/sgldisplist.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgldisplist.s

# target to build an object file
helper/sglgrid.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglgrid.o

# target to preprocess a source file
helper/sglgrid.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglgrid.i

# target to generate assembly for a file
helper/sglgrid.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglgrid.s

# target to build an object file
helper/sglhelper.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglhelper.o

# target to preprocess a source file
helper/sglhelper.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglhelper.i

# target to generate assembly for a file
helper/sglhelper.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglhelper.s

# target to build an object file
helper/sgllensflare.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllensflare.o

# target to preprocess a source file
helper/sgllensflare.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllensflare.i

# target to generate assembly for a file
helper/sgllensflare.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllensflare.s

# target to build an object file
helper/sgllight.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllight.o

# target to preprocess a source file
helper/sgllight.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllight.i

# target to generate assembly for a file
helper/sgllight.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllight.s

# target to build an object file
primitives/sglflobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglflobj.o

# target to preprocess a source file
primitives/sglflobj.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglflobj.i

# target to generate assembly for a file
primitives/sglflobj.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglflobj.s

# target to build an object file
primitives/sglgeosphere.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglgeosphere.o

# target to preprocess a source file
primitives/sglgeosphere.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglgeosphere.i

# target to generate assembly for a file
primitives/sglgeosphere.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglgeosphere.s

# target to build an object file
primitives/sglicosahedron.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglicosahedron.o

# target to preprocess a source file
primitives/sglicosahedron.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglicosahedron.i

# target to generate assembly for a file
primitives/sglicosahedron.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglicosahedron.s

# target to build an object file
primitives/sglloft.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglloft.o

# target to preprocess a source file
primitives/sglloft.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglloft.i

# target to generate assembly for a file
primitives/sglloft.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglloft.s

# target to build an object file
primitives/sglneck.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglneck.o

# target to preprocess a source file
primitives/sglneck.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglneck.i

# target to generate assembly for a file
primitives/sglneck.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglneck.s

# target to build an object file
primitives/sglpolygonobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglpolygonobj.o

# target to preprocess a source file
primitives/sglpolygonobj.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglpolygonobj.i

# target to generate assembly for a file
primitives/sglpolygonobj.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglpolygonobj.s

# target to build an object file
primitives/sglquader.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquader.o

# target to preprocess a source file
primitives/sglquader.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquader.i

# target to generate assembly for a file
primitives/sglquader.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquader.s

# target to build an object file
primitives/sglquadricobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquadricobj.o

# target to preprocess a source file
primitives/sglquadricobj.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquadricobj.i

# target to generate assembly for a file
primitives/sglquadricobj.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquadricobj.s

# target to build an object file
primitives/sglvieleck.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglvieleck.o

# target to preprocess a source file
primitives/sglvieleck.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglvieleck.i

# target to generate assembly for a file
primitives/sglvieleck.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglvieleck.s

# target to build an object file
sglmatrixobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmatrixobj.o

# target to preprocess a source file
sglmatrixobj.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmatrixobj.i

# target to generate assembly for a file
sglmatrixobj.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmatrixobj.s

# target to build an object file
sglmetaobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmetaobj.o

# target to preprocess a source file
sglmetaobj.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmetaobj.i

# target to generate assembly for a file
sglmetaobj.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmetaobj.s

# target to build an object file
sglmisc.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmisc.o

# target to preprocess a source file
sglmisc.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmisc.i

# target to generate assembly for a file
sglmisc.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmisc.s

# target to build an object file
sglobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobj.o

# target to preprocess a source file
sglobj.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobj.i

# target to generate assembly for a file
sglobj.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobj.s

# target to build an object file
sglobjbase.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobjbase.o

# target to preprocess a source file
sglobjbase.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobjbase.i

# target to generate assembly for a file
sglobjbase.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobjbase.s

# target to build an object file
sglspace.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglspace.o

# target to preprocess a source file
sglspace.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglspace.i

# target to generate assembly for a file
sglspace.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglspace.s

# target to build an object file
sglvektor.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglvektor.o

# target to preprocess a source file
sglvektor.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglvektor.i

# target to generate assembly for a file
sglvektor.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglvektor.s

# target to build an object file
text/backend_glf/glf.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/glf.o

# target to preprocess a source file
text/backend_glf/glf.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/glf.i

# target to generate assembly for a file
text/backend_glf/glf.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/glf.s

# target to build an object file
text/backend_glf/sgltextbackend_glf.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/sgltextbackend_glf.o

# target to preprocess a source file
text/backend_glf/sgltextbackend_glf.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/sgltextbackend_glf.i

# target to generate assembly for a file
text/backend_glf/sgltextbackend_glf.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/sgltextbackend_glf.s

# target to build an object file
text/sgl3dtext.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgl3dtext.o

# target to preprocess a source file
text/sgl3dtext.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgl3dtext.i

# target to generate assembly for a file
text/sgl3dtext.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgl3dtext.s

# target to build an object file
text/sglconsole.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sglconsole.o

# target to preprocess a source file
text/sglconsole.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sglconsole.i

# target to generate assembly for a file
text/sglconsole.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sglconsole.s

# target to build an object file
text/sgltext.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltext.o

# target to preprocess a source file
text/sgltext.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltext.i

# target to generate assembly for a file
text/sgltext.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltext.s

# target to build an object file
text/sgltextbackend.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltextbackend.o

# target to preprocess a source file
text/sgltextbackend.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltextbackend.i

# target to generate assembly for a file
text/sgltextbackend.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltextbackend.s

# target to build an object file
util/memconsumer.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/memconsumer.o

# target to preprocess a source file
util/memconsumer.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/memconsumer.i

# target to generate assembly for a file
util/memconsumer.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/memconsumer.s

# target to build an object file
util/readtex.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/readtex.o

# target to preprocess a source file
util/readtex.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/readtex.i

# target to generate assembly for a file
util/readtex.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/readtex.s

# target to build an object file
util/sglimagefile.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglimagefile.o

# target to preprocess a source file
util/sglimagefile.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglimagefile.i

# target to generate assembly for a file
util/sglimagefile.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglimagefile.s

# target to build an object file
util/sglmaterial.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglmaterial.o

# target to preprocess a source file
util/sglmaterial.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglmaterial.i

# target to generate assembly for a file
util/sglmaterial.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglmaterial.s

# target to build an object file
util/sgltextur.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sgltextur.o

# target to preprocess a source file
util/sgltextur.i:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sgltextur.i

# target to generate assembly for a file
util/sgltextur.s:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sgltextur.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sgl"
	@echo "... helper/sglcamera.o"
	@echo "... helper/sglcamera.i"
	@echo "... helper/sglcamera.s"
	@echo "... helper/sglclipplane.o"
	@echo "... helper/sglclipplane.i"
	@echo "... helper/sglclipplane.s"
	@echo "... helper/sgldisplist.o"
	@echo "... helper/sgldisplist.i"
	@echo "... helper/sgldisplist.s"
	@echo "... helper/sglgrid.o"
	@echo "... helper/sglgrid.i"
	@echo "... helper/sglgrid.s"
	@echo "... helper/sglhelper.o"
	@echo "... helper/sglhelper.i"
	@echo "... helper/sglhelper.s"
	@echo "... helper/sgllensflare.o"
	@echo "... helper/sgllensflare.i"
	@echo "... helper/sgllensflare.s"
	@echo "... helper/sgllight.o"
	@echo "... helper/sgllight.i"
	@echo "... helper/sgllight.s"
	@echo "... primitives/sglflobj.o"
	@echo "... primitives/sglflobj.i"
	@echo "... primitives/sglflobj.s"
	@echo "... primitives/sglgeosphere.o"
	@echo "... primitives/sglgeosphere.i"
	@echo "... primitives/sglgeosphere.s"
	@echo "... primitives/sglicosahedron.o"
	@echo "... primitives/sglicosahedron.i"
	@echo "... primitives/sglicosahedron.s"
	@echo "... primitives/sglloft.o"
	@echo "... primitives/sglloft.i"
	@echo "... primitives/sglloft.s"
	@echo "... primitives/sglneck.o"
	@echo "... primitives/sglneck.i"
	@echo "... primitives/sglneck.s"
	@echo "... primitives/sglpolygonobj.o"
	@echo "... primitives/sglpolygonobj.i"
	@echo "... primitives/sglpolygonobj.s"
	@echo "... primitives/sglquader.o"
	@echo "... primitives/sglquader.i"
	@echo "... primitives/sglquader.s"
	@echo "... primitives/sglquadricobj.o"
	@echo "... primitives/sglquadricobj.i"
	@echo "... primitives/sglquadricobj.s"
	@echo "... primitives/sglvieleck.o"
	@echo "... primitives/sglvieleck.i"
	@echo "... primitives/sglvieleck.s"
	@echo "... sglmatrixobj.o"
	@echo "... sglmatrixobj.i"
	@echo "... sglmatrixobj.s"
	@echo "... sglmetaobj.o"
	@echo "... sglmetaobj.i"
	@echo "... sglmetaobj.s"
	@echo "... sglmisc.o"
	@echo "... sglmisc.i"
	@echo "... sglmisc.s"
	@echo "... sglobj.o"
	@echo "... sglobj.i"
	@echo "... sglobj.s"
	@echo "... sglobjbase.o"
	@echo "... sglobjbase.i"
	@echo "... sglobjbase.s"
	@echo "... sglspace.o"
	@echo "... sglspace.i"
	@echo "... sglspace.s"
	@echo "... sglvektor.o"
	@echo "... sglvektor.i"
	@echo "... sglvektor.s"
	@echo "... text/backend_glf/glf.o"
	@echo "... text/backend_glf/glf.i"
	@echo "... text/backend_glf/glf.s"
	@echo "... text/backend_glf/sgltextbackend_glf.o"
	@echo "... text/backend_glf/sgltextbackend_glf.i"
	@echo "... text/backend_glf/sgltextbackend_glf.s"
	@echo "... text/sgl3dtext.o"
	@echo "... text/sgl3dtext.i"
	@echo "... text/sgl3dtext.s"
	@echo "... text/sglconsole.o"
	@echo "... text/sglconsole.i"
	@echo "... text/sglconsole.s"
	@echo "... text/sgltext.o"
	@echo "... text/sgltext.i"
	@echo "... text/sgltext.s"
	@echo "... text/sgltextbackend.o"
	@echo "... text/sgltextbackend.i"
	@echo "... text/sgltextbackend.s"
	@echo "... util/memconsumer.o"
	@echo "... util/memconsumer.i"
	@echo "... util/memconsumer.s"
	@echo "... util/readtex.o"
	@echo "... util/readtex.i"
	@echo "... util/readtex.s"
	@echo "... util/sglimagefile.o"
	@echo "... util/sglimagefile.i"
	@echo "... util/sglimagefile.s"
	@echo "... util/sglmaterial.o"
	@echo "... util/sglmaterial.i"
	@echo "... util/sglmaterial.s"
	@echo "... util/sgltextur.o"
	@echo "... util/sgltextur.i"
	@echo "... util/sgltextur.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

