# CMAKE generated file: DO NOT EDIT!
# Generated by "KDevelop3" Generator, CMake Version 2.4

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /SCR/simpleGL/libsgl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /SCR/simpleGL/libsgl

# Default target executed when no arguments are given to make.
default_target: all

# Special rule for the target edit_cache
edit_cache:
	@echo "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#=============================================================================
# Special targets provided by cmake.

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# The main all target
all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast: all
preinstall/fast: preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

# fast build rule for target.
edit_cache/fast: edit_cache

# fast build rule for target.
install/fast: install

# fast build rule for target.
rebuild_cache/fast: rebuild_cache

#=============================================================================
# Target rules for targets named sgl

# Build rule for target.
sgl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sgl

# fast build rule for target.
sgl/fast:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/build

# target for object file
helper/sglcamera.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglcamera.o

# target for object file
helper/sglclipplane.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglclipplane.o

# target for object file
helper/sgldisplist.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgldisplist.o

# target for object file
helper/sglgrid.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglgrid.o

# target for object file
helper/sglhelper.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sglhelper.o

# target for object file
helper/sgllensflare.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllensflare.o

# target for object file
helper/sgllight.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/helper/sgllight.o

# target for object file
primitives/sglflobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglflobj.o

# target for object file
primitives/sglgeosphere.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglgeosphere.o

# target for object file
primitives/sglicosahedron.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglicosahedron.o

# target for object file
primitives/sglloft.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglloft.o

# target for object file
primitives/sglneck.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglneck.o

# target for object file
primitives/sglpolygonobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglpolygonobj.o

# target for object file
primitives/sglquader.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquader.o

# target for object file
primitives/sglquadricobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglquadricobj.o

# target for object file
primitives/sglvieleck.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/primitives/sglvieleck.o

# target for object file
sglmatrixobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmatrixobj.o

# target for object file
sglmetaobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmetaobj.o

# target for object file
sglmisc.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglmisc.o

# target for object file
sglobj.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobj.o

# target for object file
sglobjbase.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglobjbase.o

# target for object file
sglspace.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglspace.o

# target for object file
sglvektor.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/sglvektor.o

# target for object file
text/backend_glf/glf.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/glf.o

# target for object file
text/backend_glf/sgltextbackend_glf.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/backend_glf/sgltextbackend_glf.o

# target for object file
text/sgl3dtext.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgl3dtext.o

# target for object file
text/sglconsole.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sglconsole.o

# target for object file
text/sgltext.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltext.o

# target for object file
text/sgltextbackend.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/text/sgltextbackend.o

# target for object file
util/memconsumer.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/memconsumer.o

# target for object file
util/readtex.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/readtex.o

# target for object file
util/sglbaseshader.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglbaseshader.o

# target for object file
util/sglfragmentshader.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglfragmentshader.o

# target for object file
util/sglimagefile.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglimagefile.o

# target for object file
util/sglmaterial.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sglmaterial.o

# target for object file
util/sgltextur.o:
	$(MAKE) -f CMakeFiles/sgl.dir/build.make CMakeFiles/sgl.dir/util/sgltextur.o

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... sgl"
	@echo "... helper/sglcamera.o"
	@echo "... helper/sglclipplane.o"
	@echo "... helper/sgldisplist.o"
	@echo "... helper/sglgrid.o"
	@echo "... helper/sglhelper.o"
	@echo "... helper/sgllensflare.o"
	@echo "... helper/sgllight.o"
	@echo "... primitives/sglflobj.o"
	@echo "... primitives/sglgeosphere.o"
	@echo "... primitives/sglicosahedron.o"
	@echo "... primitives/sglloft.o"
	@echo "... primitives/sglneck.o"
	@echo "... primitives/sglpolygonobj.o"
	@echo "... primitives/sglquader.o"
	@echo "... primitives/sglquadricobj.o"
	@echo "... primitives/sglvieleck.o"
	@echo "... sglmatrixobj.o"
	@echo "... sglmetaobj.o"
	@echo "... sglmisc.o"
	@echo "... sglobj.o"
	@echo "... sglobjbase.o"
	@echo "... sglspace.o"
	@echo "... sglvektor.o"
	@echo "... text/backend_glf/glf.o"
	@echo "... text/backend_glf/sgltextbackend_glf.o"
	@echo "... text/sgl3dtext.o"
	@echo "... text/sglconsole.o"
	@echo "... text/sgltext.o"
	@echo "... text/sgltextbackend.o"
	@echo "... util/memconsumer.o"
	@echo "... util/readtex.o"
	@echo "... util/sglbaseshader.o"
	@echo "... util/sglfragmentshader.o"
	@echo "... util/sglimagefile.o"
	@echo "... util/sglmaterial.o"
	@echo "... util/sgltextur.o"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

