export EMATH_DIR=$(HOME)/emath/

export MAKEFILE = Makefile.manual
export CXXFLAGS= -I$(EMATH_DIR) -g3 -DDATA_DIR="\"$(HOME)/data\"" -DGL_GLEXT_PROTOTYPES -DBOOST_DISABLE_THREADS
export CFLAGS=$(CXXFLAGS)

export LIBS = -L$(EMATH_DIR)
export LINK_LIBS = $(LIBS) -lm -lGL -lGLU -lEMath

%:
	${MAKE} $@ -f Makefile.manual

#$(shell sdl-config --cflags) 
#$(shell sdl-config --libs)
#-lIL -lILUT -lILU 
