# CMAKE generated Makefile, DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.0
# Generated from the following files:
# /SCR/simpleGL/libsgl/CMakeCache.txt
# /SCR/simpleGL/libsgl/CMakeCCompiler.cmake
# /SCR/simpleGL/libsgl/CMakeCXXCompiler.cmake
# /SCR/simpleGL/libsgl/CMakeLists.txt
# /SCR/simpleGL/libsgl/CMakeSystem.cmake
# /usr/share/CMake/Modules/CMakeDefaultMakeRuleVariables.cmake
# /usr/share/CMake/Modules/CMakeSystemSpecificInformation.cmake
# /usr/share/CMake/Modules/CheckFunctionExists.cmake
# /usr/share/CMake/Modules/CheckLibraryExists.cmake
# /usr/share/CMake/Modules/FindOpenGL.cmake
# /usr/share/CMake/Modules/FindX11.cmake
# /usr/share/CMake/Modules/Platform/Linux.cmake
# /usr/share/CMake/Modules/Platform/gcc.cmake


# disable some common implicit rules to speed things up
.SUFFIXES:
.SUFFIXES:.hpuxmakemusthaverule
CMAKE_MAKEFILE_SOURCES =  /SCR/simpleGL/libsgl/CMakeCCompiler.cmake /SCR/simpleGL/libsgl/CMakeCXXCompiler.cmake /SCR/simpleGL/libsgl/CMakeLists.txt /SCR/simpleGL/libsgl/CMakeSystem.cmake /usr/share/CMake/Modules/CMakeDefaultMakeRuleVariables.cmake /usr/share/CMake/Modules/CMakeSystemSpecificInformation.cmake /usr/share/CMake/Modules/CheckFunctionExists.cmake /usr/share/CMake/Modules/CheckLibraryExists.cmake /usr/share/CMake/Modules/FindOpenGL.cmake /usr/share/CMake/Modules/FindX11.cmake /usr/share/CMake/Modules/Platform/Linux.cmake /usr/share/CMake/Modules/Platform/gcc.cmake /SCR/simpleGL/libsgl/CMakeCache.txt


# the standard shell for make
SHELL = /bin/sh

CMAKE_COMMAND = /usr/bin/cmake
RM = /usr/bin/cmake -E remove -f
CMAKE_EDIT_COMMAND = /usr/bin/ccmake
CMAKE_CURRENT_SOURCE = /SCR/simpleGL/libsgl
CMAKE_CURRENT_BINARY = /SCR/simpleGL/libsgl
CMAKE_SOURCE_DIR = /SCR/simpleGL/libsgl
CMAKE_BINARY_DIR = /SCR/simpleGL/libsgl
INCLUDE_FLAGS = -I/usr/share/doc/NVIDIA_GLX-1.0/include   -DDATA_DIR=\"/SCR/simpleGL/libsgl/data\" -DGL_GLEXT_PROTOTYPES -DBOOST_HAS_PTHREADS -ffast-math -pthread -Wall

#---------------------------------------------------------
# Default target executed when no arguments are given to make, first make sure cmake.depends exists, cmake.check_depends is up-to-date, check the sources, then build the all target
#

default_target: /SCR/simpleGL/libsgl/cmake.check_cache
	$(MAKE) $(MAKESILENT) cmake.depends
	$(MAKE) $(MAKESILENT) cmake.check_depends
	$(MAKE) $(MAKESILENT) -f cmake.check_depends
	$(MAKE) $(MAKESILENT) all

# Suppresses display of executed commands
$(VERBOSE).SILENT:

help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... libsgl.so"


TARGETS =  \
libsgl.so

sgl_SRC_OBJS = \
sglmisc.o\
sglobj.o\
sglobjbase.o\
sglspace.o\
sglvektor.o\
sglmetaobj.o\
sglmatrixobj.o\
helper/sglcamera.o\
helper/sglclipplane.o\
helper/sglgrid.o\
helper/sglhelper.o\
helper/sgllight.o\
helper/sgldisplist.o\
helper/sgllensflare.o\
primitives/sglflobj.o\
primitives/sglgeosphere.o\
primitives/sglicosahedron.o\
primitives/sglloft.o\
primitives/sglneck.o\
primitives/sglpolygonobj.o\
primitives/sglquader.o\
primitives/sglvieleck.o\
primitives/sglquadricobj.o\
util/readtex.o\
util/sglmaterial.o\
util/sgltextur.o\
util/sglimagefile.o\
util/memconsumer.o\
text/sgltext.o\
text/sglconsole.o\
text/sgl3dtext.o\
text/sgltextbackend.o\
text/backend_glf/glf.o\
text/backend_glf/sgltextbackend_glf.o

sgl_EXTERNAL_OBJS = 

sgl_SRC_OBJS_QUOTED = \
"sglmisc.o" \
"sglobj.o" \
"sglobjbase.o" \
"sglspace.o" \
"sglvektor.o" \
"sglmetaobj.o" \
"sglmatrixobj.o" \
"helper/sglcamera.o" \
"helper/sglclipplane.o" \
"helper/sglgrid.o" \
"helper/sglhelper.o" \
"helper/sgllight.o" \
"helper/sgldisplist.o" \
"helper/sgllensflare.o" \
"primitives/sglflobj.o" \
"primitives/sglgeosphere.o" \
"primitives/sglicosahedron.o" \
"primitives/sglloft.o" \
"primitives/sglneck.o" \
"primitives/sglpolygonobj.o" \
"primitives/sglquader.o" \
"primitives/sglvieleck.o" \
"primitives/sglquadricobj.o" \
"util/readtex.o" \
"util/sglmaterial.o" \
"util/sgltextur.o" \
"util/sglimagefile.o" \
"util/memconsumer.o" \
"text/sgltext.o" \
"text/sglconsole.o" \
"text/sgl3dtext.o" \
"text/sgltextbackend.o" \
"text/backend_glf/glf.o" \
"text/backend_glf/sgltextbackend_glf.o" 

sgl_EXTERNAL_OBJS_QUOTED = 

TARGET_EXTRAS = 

CLEAN_OBJECT_FILES = $(sgl_SRC_OBJS) 

sgl_DEPEND_LIBS = /Software/local/lib/libMesaGLU.a /Software/local/lib/libMesaGL.a /usr/X11R6/lib/libX11.so /usr/X11R6/lib/libXext.so /usr/lib/libboost_signals.so /usr/lib/libeclasses2.so 

#---------------------------------------------------------
# shared library
#

libsgl.so: $(sgl_SRC_OBJS) $(sgl_EXTERNAL_OBJS)  $(sgl_DEPEND_LIBS)
	@echo "Building shared library libsgl.so..."
	/usr/bin/cmake -E remove -f libsgl.so
	c++ -fPIC    -shared -Wl,-soname,libsgl.so -o libsgl.so $(sgl_SRC_OBJS) $(sgl_EXTERNAL_OBJS)  -L/Software/local/lib -L/usr/X11R6/lib -lMesaGLU -lMesaGL -lSM -lICE -lX11 -lXext -lboost_signals -leclasses2 -lm -Wl,-rpath,/Software/local/lib:/usr/X11R6/lib  -lgcc

#---------------------------------------------------------
# shared library
#

sgl: libsgl.so

#---------------------------------------------------------
# default build rule
#

all: cmake.depends $(SUBDIR_PREORDER_BUILD) $(TARGETS) $(SUBDIR_BUILD)

#---------------------------------------------------------
# clean generated files
#

clean: $(SUBDIR_CLEAN)
	-@ $(RM) $(CLEAN_OBJECT_FILES)  $(TARGETS) $(TARGET_EXTRAS) $(GENERATED_QT_FILES) $(GENERATED_FLTK_FILES) $(ADDITIONAL_MAKE_CLEAN_FILES)

#---------------------------------------------------------
# dependencies.
#

cmake.depends: $(CMAKE_MAKEFILE_SOURCES)
	@echo "Building dependencies. cmake.depends..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# dependencies
#

cmake.check_depends: /SCR/simpleGL/libsgl/./sglmisc.c
cmake.check_depends: /SCR/simpleGL/libsgl/./sglobj.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/./sglobjbase.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/./sglspace.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/./sglvektor.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/./sglmetaobj.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/./sglmatrixobj.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sglcamera.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sglclipplane.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sglgrid.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sglhelper.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sgllight.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sgldisplist.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/helper/sgllensflare.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglflobj.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglgeosphere.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglicosahedron.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglloft.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglneck.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglpolygonobj.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglquader.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglvieleck.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/primitives/sglquadricobj.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/util/readtex.c
cmake.check_depends: /SCR/simpleGL/libsgl/util/sglmaterial.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/util/sgltextur.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/util/sglimagefile.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/util/memconsumer.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/text/sgltext.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/text/sglconsole.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/text/sgl3dtext.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/text/sgltextbackend.cpp
cmake.check_depends: /SCR/simpleGL/libsgl/text/backend_glf/glf.c
cmake.check_depends: /SCR/simpleGL/libsgl/text/backend_glf/sgltextbackend_glf.cpp
	@echo "Building dependencies cmake.check_depends..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# dependencies
#

depend: $(SUBDIR_DEPEND)
	@echo "Building dependencies depend..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# dependencies
#

dependlocal:
	@echo "Building dependencies dependlocal..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# CMakeCache.txt
#

rebuild_cache:
	@echo "Building CMakeCache.txt rebuild_cache..."
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# CMakeCache.txt because out-of-date:
#

/SCR/simpleGL/libsgl/cmake.check_cache: $(CMAKE_MAKEFILE_SOURCES)
	@echo "Building CMakeCache.txt because out-of-date: /SCR/simpleGL/libsgl/cmake.check_cache..."
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# edit CMakeCache.txt
#

edit_cache:
	@echo "Building edit CMakeCache.txt edit_cache..."
	$(CMAKE_EDIT_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# CMakeCache.txt
#

/SCR/simpleGL/libsgl/CMakeCache.txt:
	@echo "Building CMakeCache.txt /SCR/simpleGL/libsgl/CMakeCache.txt..."
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# Rule to keep make from removing Makefiles if control-C is hit during a run of cmake.
#

.PRECIOUS: Makefile cmake.depends

# Rules to build .o files from their sources:
#---------------------------------------------------------
# object file
#

sglmisc.o: /SCR/simpleGL/libsgl/./sglmisc.c
	@echo "Building object file ./sglmisc.o..."
	gcc -o ./sglmisc.o  -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglmisc.c

#---------------------------------------------------------
# object file
#

sglobj.o: /SCR/simpleGL/libsgl/./sglobj.cpp
	@echo "Building object file ./sglobj.o..."
	c++ -o ./sglobj.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglobj.cpp

#---------------------------------------------------------
# object file
#

sglobjbase.o: /SCR/simpleGL/libsgl/./sglobjbase.cpp
	@echo "Building object file ./sglobjbase.o..."
	c++ -o ./sglobjbase.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglobjbase.cpp

#---------------------------------------------------------
# object file
#

sglspace.o: /SCR/simpleGL/libsgl/./sglspace.cpp
	@echo "Building object file ./sglspace.o..."
	c++ -o ./sglspace.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglspace.cpp

#---------------------------------------------------------
# object file
#

sglvektor.o: /SCR/simpleGL/libsgl/./sglvektor.cpp
	@echo "Building object file ./sglvektor.o..."
	c++ -o ./sglvektor.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglvektor.cpp

#---------------------------------------------------------
# object file
#

sglmetaobj.o: /SCR/simpleGL/libsgl/./sglmetaobj.cpp
	@echo "Building object file ./sglmetaobj.o..."
	c++ -o ./sglmetaobj.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglmetaobj.cpp

#---------------------------------------------------------
# object file
#

sglmatrixobj.o: /SCR/simpleGL/libsgl/./sglmatrixobj.cpp
	@echo "Building object file ./sglmatrixobj.o..."
	c++ -o ./sglmatrixobj.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/./sglmatrixobj.cpp

#---------------------------------------------------------
# object file
#

helper/sglcamera.o: /SCR/simpleGL/libsgl/helper/sglcamera.cpp
	@echo "Building object file helper/sglcamera.o..."
	c++ -o helper/sglcamera.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sglcamera.cpp

#---------------------------------------------------------
# object file
#

helper/sglclipplane.o: /SCR/simpleGL/libsgl/helper/sglclipplane.cpp
	@echo "Building object file helper/sglclipplane.o..."
	c++ -o helper/sglclipplane.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sglclipplane.cpp

#---------------------------------------------------------
# object file
#

helper/sglgrid.o: /SCR/simpleGL/libsgl/helper/sglgrid.cpp
	@echo "Building object file helper/sglgrid.o..."
	c++ -o helper/sglgrid.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sglgrid.cpp

#---------------------------------------------------------
# object file
#

helper/sglhelper.o: /SCR/simpleGL/libsgl/helper/sglhelper.cpp
	@echo "Building object file helper/sglhelper.o..."
	c++ -o helper/sglhelper.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sglhelper.cpp

#---------------------------------------------------------
# object file
#

helper/sgllight.o: /SCR/simpleGL/libsgl/helper/sgllight.cpp
	@echo "Building object file helper/sgllight.o..."
	c++ -o helper/sgllight.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sgllight.cpp

#---------------------------------------------------------
# object file
#

helper/sgldisplist.o: /SCR/simpleGL/libsgl/helper/sgldisplist.cpp
	@echo "Building object file helper/sgldisplist.o..."
	c++ -o helper/sgldisplist.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sgldisplist.cpp

#---------------------------------------------------------
# object file
#

helper/sgllensflare.o: /SCR/simpleGL/libsgl/helper/sgllensflare.cpp
	@echo "Building object file helper/sgllensflare.o..."
	c++ -o helper/sgllensflare.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/helper/sgllensflare.cpp

#---------------------------------------------------------
# object file
#

primitives/sglflobj.o: /SCR/simpleGL/libsgl/primitives/sglflobj.cpp
	@echo "Building object file primitives/sglflobj.o..."
	c++ -o primitives/sglflobj.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglflobj.cpp

#---------------------------------------------------------
# object file
#

primitives/sglgeosphere.o: /SCR/simpleGL/libsgl/primitives/sglgeosphere.cpp
	@echo "Building object file primitives/sglgeosphere.o..."
	c++ -o primitives/sglgeosphere.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglgeosphere.cpp

#---------------------------------------------------------
# object file
#

primitives/sglicosahedron.o: /SCR/simpleGL/libsgl/primitives/sglicosahedron.cpp
	@echo "Building object file primitives/sglicosahedron.o..."
	c++ -o primitives/sglicosahedron.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglicosahedron.cpp

#---------------------------------------------------------
# object file
#

primitives/sglloft.o: /SCR/simpleGL/libsgl/primitives/sglloft.cpp
	@echo "Building object file primitives/sglloft.o..."
	c++ -o primitives/sglloft.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglloft.cpp

#---------------------------------------------------------
# object file
#

primitives/sglneck.o: /SCR/simpleGL/libsgl/primitives/sglneck.cpp
	@echo "Building object file primitives/sglneck.o..."
	c++ -o primitives/sglneck.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglneck.cpp

#---------------------------------------------------------
# object file
#

primitives/sglpolygonobj.o: /SCR/simpleGL/libsgl/primitives/sglpolygonobj.cpp
	@echo "Building object file primitives/sglpolygonobj.o..."
	c++ -o primitives/sglpolygonobj.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglpolygonobj.cpp

#---------------------------------------------------------
# object file
#

primitives/sglquader.o: /SCR/simpleGL/libsgl/primitives/sglquader.cpp
	@echo "Building object file primitives/sglquader.o..."
	c++ -o primitives/sglquader.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglquader.cpp

#---------------------------------------------------------
# object file
#

primitives/sglvieleck.o: /SCR/simpleGL/libsgl/primitives/sglvieleck.cpp
	@echo "Building object file primitives/sglvieleck.o..."
	c++ -o primitives/sglvieleck.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglvieleck.cpp

#---------------------------------------------------------
# object file
#

primitives/sglquadricobj.o: /SCR/simpleGL/libsgl/primitives/sglquadricobj.cpp
	@echo "Building object file primitives/sglquadricobj.o..."
	c++ -o primitives/sglquadricobj.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/primitives/sglquadricobj.cpp

#---------------------------------------------------------
# object file
#

util/readtex.o: /SCR/simpleGL/libsgl/util/readtex.c
	@echo "Building object file util/readtex.o..."
	gcc -o util/readtex.o  -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/util/readtex.c

#---------------------------------------------------------
# object file
#

util/sglmaterial.o: /SCR/simpleGL/libsgl/util/sglmaterial.cpp
	@echo "Building object file util/sglmaterial.o..."
	c++ -o util/sglmaterial.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/util/sglmaterial.cpp

#---------------------------------------------------------
# object file
#

util/sgltextur.o: /SCR/simpleGL/libsgl/util/sgltextur.cpp
	@echo "Building object file util/sgltextur.o..."
	c++ -o util/sgltextur.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/util/sgltextur.cpp

#---------------------------------------------------------
# object file
#

util/sglimagefile.o: /SCR/simpleGL/libsgl/util/sglimagefile.cpp
	@echo "Building object file util/sglimagefile.o..."
	c++ -o util/sglimagefile.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/util/sglimagefile.cpp

#---------------------------------------------------------
# object file
#

util/memconsumer.o: /SCR/simpleGL/libsgl/util/memconsumer.cpp
	@echo "Building object file util/memconsumer.o..."
	c++ -o util/memconsumer.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/util/memconsumer.cpp

#---------------------------------------------------------
# object file
#

text/sgltext.o: /SCR/simpleGL/libsgl/text/sgltext.cpp
	@echo "Building object file text/sgltext.o..."
	c++ -o text/sgltext.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/text/sgltext.cpp

#---------------------------------------------------------
# object file
#

text/sglconsole.o: /SCR/simpleGL/libsgl/text/sglconsole.cpp
	@echo "Building object file text/sglconsole.o..."
	c++ -o text/sglconsole.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/text/sglconsole.cpp

#---------------------------------------------------------
# object file
#

text/sgl3dtext.o: /SCR/simpleGL/libsgl/text/sgl3dtext.cpp
	@echo "Building object file text/sgl3dtext.o..."
	c++ -o text/sgl3dtext.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/text/sgl3dtext.cpp

#---------------------------------------------------------
# object file
#

text/sgltextbackend.o: /SCR/simpleGL/libsgl/text/sgltextbackend.cpp
	@echo "Building object file text/sgltextbackend.o..."
	c++ -o text/sgltextbackend.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/text/sgltextbackend.cpp

#---------------------------------------------------------
# object file
#

text/backend_glf/glf.o: /SCR/simpleGL/libsgl/text/backend_glf/glf.c
	@echo "Building object file text/backend_glf/glf.o..."
	gcc -o text/backend_glf/glf.o  -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/text/backend_glf/glf.c

#---------------------------------------------------------
# object file
#

text/backend_glf/sgltextbackend_glf.o: /SCR/simpleGL/libsgl/text/backend_glf/sgltextbackend_glf.cpp
	@echo "Building object file text/backend_glf/sgltextbackend_glf.o..."
	c++ -o text/backend_glf/sgltextbackend_glf.o -Dsgl_EXPORTS  -g3 -fPIC $(INCLUDE_FLAGS)  -c /SCR/simpleGL/libsgl/text/backend_glf/sgltextbackend_glf.cpp

#---------------------------------------------------------
# installation
#

install: 
	@echo "Building installation install..."
	$(CMAKE_COMMAND) -P cmake_install.cmake

include cmake.depends
