export CC=icc
export CXX=icc
export MAKEFILE = Makefile.manual
export CXXFLAGS= -I/opt/prog/eclasses/eclasses2 -fPIC -xB -O3 -DDATA_DIR="\"./data\"" -DGL_GLEXT_PROTOTYPES -pthread
export CFLAGS=$(CXXFLAGS)


%:
	${MAKE} $@ -f Makefile.manual

