export EMATH_DIR=$(HOME)/emath/

export MAKEFILE = Makefile.manual
export CXXFLAGS= -I$(EMATH_DIR) -fPIC -O2 -DDATA_DIR="\"./data\"" -DGL_GLEXT_PROTOTYPES -pthread

export CFLAGS=$(CXXFLAGS)
#
export LIBS = -L$(EMATH_DIR)
export LINK_LIBS = $(LIBS) -lm -lGL -lGLU -lEMath

%:
	${MAKE} $@ -f Makefile.manual

#$(shell sdl-config --cflags) 
#$(shell sdl-config --libs)
#-lIL -lILUT -lILU 
