Document: libsgl-qtglue
Title: Debian libsgl-qtglue Manual
Author: <insert document author here>
Abstract: This manual describes what libsgl-qtglue is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsgl-qtglue/libsgl-qtglue.sgml.gz

Format: postscript
Files: /usr/share/doc/libsgl-qtglue/libsgl-qtglue.ps.gz

Format: text
Files: /usr/share/doc/libsgl-qtglue/libsgl-qtglue.text.gz

Format: HTML
Index: /usr/share/doc/libsgl-qtglue/html/index.html
Files: /usr/share/doc/libsgl-qtglue/html/*.html

  
