Document: sgl
Title: Debian sgl Manual
Author: <insert document author here>
Abstract: This manual describes what sgl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sgl/sgl.sgml.gz

Format: postscript
Files: /usr/share/doc/sgl/sgl.ps.gz

Format: text
Files: /usr/share/doc/sgl/sgl.text.gz

Format: HTML
Index: /usr/share/doc/sgl/html/index.html
Files: /usr/share/doc/sgl/html/*.html

  
